image: gitlab.labs.g2-inc.net:4567/screamingbunny/docker/plus:centos-python2

variables:
  GIT_SSL_NO_VERIFY: "true"
  JQ_LINUX64: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
  VERSION_FILE: ./version.json

before_script:
  - yum -y install wget
  - if [ ! -f /tmp/jq ]; then wget $JQ_LINUX64 -qO /tmp/jq; chmod 755 /tmp/jq; fi
  # Configure Version file
  - echo "$(/tmp/jq --arg NUM ${CI_PIPELINE_ID} '.version.pipe_number=$NUM' $VERSION_FILE)" > $VERSION_FILE
  - echo "$(/tmp/jq --arg SHA_HASH ${CI_COMMIT_SHA:0:8} '.version.hash=$SHA_HASH' $VERSION_FILE)" > $VERSION_FILE
  - echo "$(/tmp/jq --arg DATE $(date +%Y-%m-%d) '.version.date=$DATE' $VERSION_FILE)" > $VERSION_FILE
  - echo "$(/tmp/jq --arg PKG ${PKG_NAME} '.pkg_name=$PKG' $VERSION_FILE)" > $VERSION_FILE
  # Configure Python Env
  - pip install -r ./requirements.txt

# Copy and edit this stage for Unit/Code Testing
#Test-Scripts:
#  stage: test
#
#  script:
#    - cd jadn
#    - python test_codec.py
#    - python test_openc2.py
#    # - python test_openc2_exp.py

Translate-Schemas:
  stage: test

  script:
    - cd jadn
    - python schema-translators.py
    - $(rm -r ../schema_gen && mkdir -p ../schema_gen) || mkdir -p ../schema_gen
    - mv ./schema_gen_test/* ../schema_gen

  artifacts:
    name: "JADN_Translations.${CI_PIPELINE_ID}_${CI_COMMIT_SHA:0:8}"
    expire_in: 2 weeks
    paths:
     - ./schema_gen/*


Build-Wheel:
  stage: deploy

  script:
    - pip wheel . -w ./dist

  artifacts:
    name: "JADN_Python.${CI_PIPELINE_ID}_${CI_COMMIT_SHA:0:8}"
    expire_in: 2 weeks
    paths:
     - ./dist/*.whl
